# Generated by Django 4.2.4 on 2023-09-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='meta_description',
        ),
        migrations.AlterField(
            model_name='brand',
            name='meta_title',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
