# Generated by Django 4.2.4 on 2023-09-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_remove_brand_meta_description_alter_brand_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='meta_description',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
